apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-microk8s-hps
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi