apiVersion: apps/v1
kind: Deployment
metadata:
  name: empty-deployment
  labels:
    app: empty-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: empty-nginx
  template:
    metadata:
      labels:
        app: empty-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.16
          ports:
            - containerPort: 80
          volumeMounts:
            - name: shared-data
              mountPath: /usr/share/nginx/html
      volumes:
        - name: shared-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: empty-nginx-service
spec:
  type: NodePort
  selector:
    app: empty-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80