apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-reviews-depl
  labels:
    app: backend-reviews
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend-reviews
  template:
    metadata:
      labels:
        app: backend-reviews
    spec:
      containers:
      - name: backend-reviews
        image: chaphe/backend-reviews-image:simple
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-reviews-service
spec:
  type: NodePort
  selector:
    app: backend-reviews
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30101