apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-pvc-depl
  labels:
    app: httpd-pvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd-pvc
  template:
    metadata:
      labels:
        app: httpd-pvc
    spec:
      containers:
        - name: httpd
          image: httpd:2.4
          ports:
            - containerPort: 80
          volumeMounts:
            - name: mypd
              mountPath: /usr/local/apache2/htdocs/
      volumes:
        - name: mypd
          persistentVolumeClaim:
            claimName: pvc-test
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-pvc-service
spec:
  type: NodePort
  selector:
    app: httpd-pvc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80