apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pvc-depl
  labels:
    app: nginx-pvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-pvc
  template:
    metadata:
      labels:
        app: nginx-pvc
    spec:
      containers:
        - name: nginx
          image: nginx:1.16
          ports:
            - containerPort: 80
          volumeMounts:
            - name: mypd
              mountPath: /usr/share/nginx/html
      volumes:
        - name: mypd
          persistentVolumeClaim:
            claimName: pvc-test

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-pvc-service
spec:
  type: NodePort
  selector:
    app: nginx-pvc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80