apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pvc-manual-depl
  labels:
    app: nginx-pvc-manual
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-pvc-manual
  template:
    metadata:
      labels:
        app: nginx-pvc-manual
    spec:
      containers:
        - name: nginx
          image: nginx:1.16
          ports:
            - containerPort: 80
          volumeMounts:
            - name: mypd
              mountPath: /usr/share/nginx/html
      volumes:
        - name: mypd
          persistentVolumeClaim:
            claimName: pvc-manual

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-pvc-manual-service
spec:
  type: NodePort
  selector:
    app: nginx-pvc-manual
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80