apiVersion: apps/v1
kind: Deployment
metadata:
  name: hp-deployment
  labels:
    app: hp-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hp-nginx
  template:
    metadata:
      labels:
        app: hp-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.16
          ports:
            - containerPort: 80
          volumeMounts:
            - name: node-data
              mountPath: /usr/share/nginx/html
      volumes:
        - name: node-data
          hostPath:
            path: /my-data
---
apiVersion: v1
kind: Service
metadata:
  name: hp-nginx-service
spec:
  type: NodePort
  selector:
    app: hp-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80